name: Build and Push Zarf GHCR Image

on:
  push:
    paths:
      - zarf/**
      - .github/workflows/zarf.yaml
    branches:
      - main

env:
  TAG: v0.28.4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./zarf
        tags: ghcr.io/meganwolf0/zarf:${{ env.TAG }}
        push: true
        build-args: |
          ZARF_VER=${{ env.TAG }}
